# Generated by Django 3.2.13 on 2022-11-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
