# Generated by Django 3.2.13 on 2022-11-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_comment_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommend',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_avg',
            field=models.FloatField(),
        ),
    ]
