# Generated by Django 3.2.13 on 2022-11-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vote_avg',
            field=models.FloatField(),
        ),
    ]
